version: '3.8'

services:
  frontend:
    build:
      context: ./movie-review-frontend
    ports:
      - "3000:80"  # Assuming your frontend app runs on port 80 inside the container
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/movie_review_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"  # Enclose true in quotes
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_review_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Use a volume for persistent MySQL data

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge
